- name: Uninstall Apache on Web server
  hosts: 
    - Ubuntuservers
    - AmzLinuxservers
  vars:
    apps:
      - apache2
      - php
  tasks:
    - name: Uninstall Apache server (feature)
      apt:
        name: "{{ apps }}"
        state: absent
      become: true
